name: Dump

on: push

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/dump
        id: dump
        with:
          enable-context: 'true'

      - name: Print dumped date
        run: echo "${DATE}"
        env:
          DATE: ${{ steps.dump.outputs.dumped-date }}